namespace Mastermind
{
    [bindable]
    [default_interface]
    runtimeclass BoardViewModel 
    {
        BoardViewModel();
        Windows.Foundation.Collections.IVector<IInspectable> Rows;
    }
}
