namespace Mastermind
{
    [bindable]
    [default_interface]
    runtimeclass ResultViewModel : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        ResultViewModel();
        //color
        Windows.UI.Color Color;
    }
}
