import "ColorViewModel.idl";

namespace Mastermind
{
    [default_interface]
    runtimeclass SelectColor : Microsoft.UI.Xaml.Controls.UserControl, Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        SelectColor();
        static Microsoft.UI.Xaml.DependencyProperty MainColorProperty{ get; };
        ColorViewModel MainColor;
        static Microsoft.UI.Xaml.DependencyProperty EnabledProperty{ get; };
        Boolean Enabled;
        static Microsoft.UI.Xaml.DependencyProperty ColorsProperty{ get; };
        Windows.Foundation.Collections.IVector<IInspectable> Colors;
    }
}
